import type { Project } from "@/content/types";

const tutorialRole = {
  en: "Full Video Production, Recording, Screen & Game Capture, Editing, Tutorial Structure, Captions & Callouts",
  tr: "Tüm Video Prodüksiyonu, Kayıt, Ekran ve Oyun Kaydı, Kurgu, Rehber Yapısı, Altyazılar ve Açıklamalar",
};

const entertainmentRole = {
  en: "Full Video Production, Recording, Game Capture, Editing, Captions & Callouts",
  tr: "Tüm Video Prodüksiyonu, Kayıt, Oyun Kaydı, Kurgu, Altyazılar ve Açıklamalar",
};

const automotiveRole = {
  en: "Editing & Visual Effects",
  tr: "Kurgu ve Görsel Efektler",
};

export const projects: Project[] = [
  {
    id: "youtube-q47Fa_4U9Q0",
    title: {
      en: "Assetto Corsa Content Manager & Mod Setup Guide",
      tr: "Assetto Corsa Content Manager ve Mod Kurulum Rehberi",
    },
    description: {
      en: "A structured long-form guide moving from desktop setup and Content Manager configuration to clear in-game verification.",
      tr: "Masaüstü kurulumu ve Content Manager yapılandırmasını anlaşılır oyun içi kontrollerle birleştiren yapılandırılmış uzun format rehber.",
    },
    format: { en: "Long-form Tutorial", tr: "Uzun Format Rehber" },
    platform: { en: "YouTube", tr: "YouTube" },
    role: tutorialRole,
    year: "2026",
    tools: ["Adobe Premiere Pro 2026"],
    tags: [{ en: "Tutorial", tr: "Rehber" }],
    posterPath: "/media/projects/youtube-02-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/projects/youtube-02-preview.mp4",
    externalUrl: "https://www.youtube.com/watch?v=q47Fa_4U9Q0",
    status: "ready",
    orientation: "landscape",
  },
  {
    id: "youtube-w0ZkuiOucCo",
    title: {
      en: "BeamNG Performance Settings Guide",
      tr: "BeamNG Performans ve FPS Ayarları Rehberi",
    },
    description: {
      en: "A performance-focused tutorial using settings capture, side-by-side comparisons, and gameplay evidence to keep technical choices clear.",
      tr: "Teknik tercihleri anlaşılır kılmak için ayar kayıtlarını, yan yana karşılaştırmaları ve oynanış kanıtını kullanan performans odaklı rehber.",
    },
    format: { en: "Long-form Tutorial", tr: "Uzun Format Rehber" },
    platform: { en: "YouTube", tr: "YouTube" },
    role: tutorialRole,
    year: "2026",
    tools: ["Adobe Premiere Pro 2026"],
    tags: [{ en: "Tutorial", tr: "Rehber" }],
    posterPath: "/media/projects/youtube-01-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/projects/youtube-01-preview.mp4",
    externalUrl: "https://www.youtube.com/watch?v=w0ZkuiOucCo",
    status: "ready",
    orientation: "landscape",
  },
  {
    id: "youtube-dnbg1JSiAQQ",
    title: {
      en: "BeamNG Cargo Run Without Fuel",
      tr: "BeamNG'de Benzinsiz Yük Taşıdım",
    },
    description: {
      en: "A self-produced entertainment edit shaped through multi-view game capture, captions, callouts, and narrative pacing.",
      tr: "Farklı açılardan oyun kaydı, altyazılar, açıklamalar ve anlatı temposuyla şekillenen, bağımsız üretilmiş eğlence videosu.",
    },
    format: { en: "Long-form Entertainment", tr: "Uzun Format Eğlence" },
    platform: { en: "YouTube", tr: "YouTube" },
    role: entertainmentRole,
    year: "2026",
    tools: ["Adobe Premiere Pro 2026"],
    tags: [{ en: "Entertainment", tr: "Eğlence" }],
    posterPath: "/media/projects/youtube-04-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/projects/youtube-04-preview.mp4",
    externalUrl: "https://www.youtube.com/watch?v=dnbg1JSiAQQ",
    status: "ready",
    orientation: "landscape",
  },
  {
    id: "youtube-FzZYNCiZrNg",
    title: {
      en: "Why Does This Car Handle Like This? | AC Rally #3",
      tr: "Bu Araba Neden Böyle? | AC Rally #3",
    },
    description: {
      en: "A self-produced rally episode built from game capture, summary framing, captions, and gameplay pacing.",
      tr: "Oyun kaydı, özet kurgusu, altyazılar ve oynanış temposuyla hazırlanan bağımsız rally bölümü.",
    },
    format: { en: "Long-form Entertainment", tr: "Uzun Format Eğlence" },
    platform: { en: "YouTube", tr: "YouTube" },
    role: entertainmentRole,
    year: "2026",
    tools: ["Adobe Premiere Pro 2026"],
    tags: [{ en: "Entertainment", tr: "Eğlence" }],
    posterPath: "/media/projects/youtube-03-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/projects/youtube-03-preview.mp4",
    externalUrl: "https://www.youtube.com/watch?v=FzZYNCiZrNg",
    status: "ready",
    orientation: "landscape",
  },
  {
    id: "automotive-vertical",
    title: { en: "Vertical Automotive Motion Edit", tr: "Dikey Otomotiv Kurgusu" },
    description: {
      en: "A fast-paced short-form study of rhythm, transitions, and visual effects. Edited using third-party footage; editing and visual effects by Ali.",
      tr: "Ritim, geçişler ve görsel efektlere odaklanan hızlı tempolu kısa format çalışma. Üçüncü taraf görüntüler kullanılarak kurgulandı; kurgu ve görsel efektler Ali tarafından hazırlandı.",
    },
    format: { en: "Short-form", tr: "Kısa Format" },
    platform: { en: "Personal Project", tr: "Kişisel Proje" },
    role: automotiveRole,
    year: "2025",
    tools: ["Adobe After Effects 2025"],
    tags: [{ en: "Supporting Work", tr: "Destekleyici İş" }],
    posterPath: "/media/automotive/automotive-vertical-poster.webp",
    posterWidth: 720,
    posterHeight: 1280,
    previewVideoPath: "/media/automotive/automotive-vertical-preview.mp4",
    externalUrl: null,
    status: "ready",
    orientation: "portrait",
  },
  {
    id: "automotive-horizontal",
    title: { en: "Cinematic Automotive Motion Edit", tr: "Sinematik Otomotiv Kurgusu" },
    description: {
      en: "A cinematic pacing and visual-effects study built around shot scale, motion, and stylized transitions. Edited using third-party footage; editing and visual effects by Ali.",
      tr: "Plan ölçeği, hareket ve stilize geçişler etrafında kurulan sinematik tempo ve görsel efekt çalışması. Üçüncü taraf görüntüler kullanılarak kurgulandı; kurgu ve görsel efektler Ali tarafından hazırlandı.",
    },
    format: { en: "Motion & Social", tr: "Motion ve Sosyal" },
    platform: { en: "Personal Project", tr: "Kişisel Proje" },
    role: automotiveRole,
    year: "2025",
    tools: ["Adobe After Effects 2025"],
    tags: [{ en: "Supporting Work", tr: "Destekleyici İş" }],
    posterPath: "/media/automotive/automotive-horizontal-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/automotive/automotive-horizontal-preview.mp4",
    externalUrl: null,
    status: "ready",
    orientation: "landscape",
  },
];
