import type { Project } from "@/content/types";

const publishedDescription = {
  en: "Published long-form work from the N0STHER YouTube channel.",
  tr: "N0STHER YouTube kanalında yayınlanan uzun format çalışma.",
};

const youtubeRole = {
  en: "Full Video Production, Recording, Editing & Sound Design",
  tr: "Tüm Video Prodüksiyonu, Kayıt, Kurgu ve Ses Tasarımı",
};

const automotiveRole = {
  en: "Editing & Visual Effects",
  tr: "Kurgu ve Görsel Efektler",
};

export const projects: Project[] = [
  {
    id: "youtube-w0ZkuiOucCo",
    title: {
      en: "Beamng En iyi FPS Ayarları | Ayarlar, Tavsiyeler ve Açıklamalar | Güncel 2026 |",
      tr: "Beamng En iyi FPS Ayarları | Ayarlar, Tavsiyeler ve Açıklamalar | Güncel 2026 |",
    },
    description: publishedDescription,
    format: { en: "Long-form", tr: "Uzun video" },
    platform: { en: "YouTube", tr: "YouTube" },
    role: youtubeRole,
    year: "2026",
    tools: ["Adobe Premiere Pro 2026"],
    tags: [{ en: "Gaming", tr: "Gaming" }],
    posterPath: "/media/projects/youtube-01-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/projects/youtube-01-preview.mp4",
    externalUrl: "https://www.youtube.com/watch?v=w0ZkuiOucCo",
    status: "ready",
    orientation: "landscape",
  },
  {
    id: "youtube-q47Fa_4U9Q0",
    title: {
      en: "Assetto Corsa Detaylı Content Manager ve Mod Kurulum Rehberi | Güncel 2026 |",
      tr: "Assetto Corsa Detaylı Content Manager ve Mod Kurulum Rehberi | Güncel 2026 |",
    },
    description: publishedDescription,
    format: { en: "Long-form", tr: "Uzun video" },
    platform: { en: "YouTube", tr: "YouTube" },
    role: youtubeRole,
    year: "2026",
    tools: ["Adobe Premiere Pro 2026"],
    tags: [{ en: "Automotive", tr: "Automotive" }],
    posterPath: "/media/projects/youtube-02-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/projects/youtube-02-preview.mp4",
    externalUrl: "https://www.youtube.com/watch?v=q47Fa_4U9Q0",
    status: "ready",
    orientation: "landscape",
  },
  {
    id: "youtube-dnbg1JSiAQQ",
    title: {
      en: "Beamng'de Benzinsiz Yük Taşıdım (Çalıştım)",
      tr: "Beamng'de Benzinsiz Yük Taşıdım (Çalıştım)",
    },
    description: publishedDescription,
    format: { en: "Long-form", tr: "Uzun video" },
    platform: { en: "YouTube", tr: "YouTube" },
    role: youtubeRole,
    year: "2026",
    tools: ["Adobe Premiere Pro 2026"],
    tags: [{ en: "Gaming", tr: "Gaming" }],
    posterPath: "/media/projects/youtube-04-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/projects/youtube-04-preview.mp4",
    externalUrl: "https://www.youtube.com/watch?v=dnbg1JSiAQQ",
    status: "ready",
    orientation: "landscape",
  },
  {
    id: "youtube-FzZYNCiZrNg",
    title: {
      en: "Bu Araba Neden Böyle... | Ac Rally | Part #3",
      tr: "Bu Araba Neden Böyle... | Ac Rally | Part #3",
    },
    description: publishedDescription,
    format: { en: "Long-form", tr: "Uzun video" },
    platform: { en: "YouTube", tr: "YouTube" },
    role: youtubeRole,
    year: "2026",
    tools: ["Adobe Premiere Pro 2026"],
    tags: [{ en: "Automotive", tr: "Automotive" }],
    posterPath: "/media/projects/youtube-03-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/projects/youtube-03-preview.mp4",
    externalUrl: "https://www.youtube.com/watch?v=FzZYNCiZrNg",
    status: "ready",
    orientation: "landscape",
  },
  {
    id: "automotive-vertical",
    title: { en: "Vertical Automotive Edit", tr: "Dikey Automotive Edit" },
    description: {
      en: "A fast-paced vertical automotive edit created from third-party footage, focused on rhythm, transitions and short-form impact.",
      tr: "Üçüncü taraf görüntüler kullanılarak hazırlanan; ritim, geçişler ve kısa format etkisine odaklanan hızlı tempolu dikey otomotiv editi.",
    },
    format: { en: "Short-form", tr: "Kısa video" },
    platform: { en: "Personal Project", tr: "Kişisel Proje" },
    role: automotiveRole,
    year: "2025",
    tools: ["Adobe After Effects 2025"],
    tags: [{ en: "Automotive", tr: "Automotive" }],
    posterPath: "/media/automotive/automotive-vertical-poster.webp",
    posterWidth: 720,
    posterHeight: 1280,
    previewVideoPath: "/media/automotive/automotive-vertical-preview.mp4",
    externalUrl: null,
    status: "ready",
    orientation: "portrait",
  },
  {
    id: "automotive-horizontal",
    title: { en: "Horizontal Automotive Edit", tr: "Yatay Automotive Edit" },
    description: {
      en: "A cinematic automotive edit created from third-party footage, focused on pacing, motion and music synchronization.",
      tr: "Üçüncü taraf görüntüler kullanılarak hazırlanan; tempo, hareket ve müzik senkronuna odaklanan sinematik yatay otomotiv editi.",
    },
    format: { en: "Motion & Social", tr: "Motion ve Sosyal" },
    platform: { en: "Personal Project", tr: "Kişisel Proje" },
    role: automotiveRole,
    year: "2025",
    tools: ["Adobe After Effects 2025"],
    tags: [{ en: "Automotive", tr: "Automotive" }],
    posterPath: "/media/automotive/automotive-horizontal-poster.webp",
    posterWidth: 1280,
    posterHeight: 720,
    previewVideoPath: "/media/automotive/automotive-horizontal-preview.mp4",
    externalUrl: null,
    status: "ready",
    orientation: "landscape",
  },
];
